# Install pre-commit hooks via
# pre-commit install

repos:
- repo: https://github.com/pre-commit/mirrors-yapf
  rev: v0.32.0
  hooks:
  - id: yapf
    name: yapf
    types: [python]
    args: ['-i']
    exclude: &exclude_files >
      (?x)^(
        sportran/utils/obsolete/.*|
        sportran_gui/utils/tk_html_widgets/*.py|
        docs/.*|
        tests/test_cli/.*|
        examples/.*|
        setup.py|
      )$
    additional_dependencies: ['toml']

- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v4.1.0
  hooks:
  - id: check-ast
  - id: check-builtin-literals
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-json
  - id: check-merge-conflict
  - id: check-shebang-scripts-are-executable
  - id: check-symlinks
  - id: check-toml
  - id: check-yaml
  - id: double-quote-string-fixer
  - id: fix-encoding-pragma
  - id: end-of-file-fixer
    exclude: >
      (?x)^(
        tests/test_cli/.*|
        sportran/utils/obsolete/.*|
      )$
  - id: trailing-whitespace
    exclude: >
      (?x)^(
        sportran/utils/obsolete/.*|
        sportran_gui/utils/tk_html_widgets/.*py|
        docs/.*|
        tests/test_cli/.*|
        tests/test_notebooks/.*|
        examples/.*|
      )$
#
#-  repo: https://github.com/PyCQA/pylint
#   rev: v2.12.2
#   hooks:
#   - id: pylint
#     language: system
#     exclude: *exclude_files
